# Generated by Django 4.2.4 on 2023-09-03 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ims1', '0002_form'),
    ]

    operations = [
        migrations.DeleteModel(
            name='form',
        ),
        migrations.RenameField(
            model_name='order_ims',
            old_name='item',
            new_name='item_id',
        ),
        migrations.AlterField(
            model_name='inventory_ims',
            name='iin',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
